### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by obscurerichard** [intel352/vagrant-bootstrap#1]
Would you consider adding a license file to this project?

For maximum compatibility with other Vagrant projects, I'd suggest the MIT license, such as expressed here:

https://github.com/intel352/vagrant-shell-scripts/blob/master/LICENSE.md

(replace the copyright statement with your copyright, of course)

**Comment by obscurerichard** [comment]
Pretty please consider adding a license file?

**Comment by intel352** [comment]
Done

**Comment by obscurerichard** [comment]
Thank you!
